#!/usr/bin/env bash

# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# CONFIG
# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  2
yabai -m config bottom_padding               2
yabai -m config left_padding                 2
yabai -m config right_padding                2
yabai -m config window_gap                   2

# RULES
# excepted applications
yabai -m rule --add app="^Finder$" layer=above manage=on mouse_follows_focus=on
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=on space=^9 mouse_follows_focus=on
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^Private Internet Access$" manage=off
yabai -m rule --add app="^BlueStacks$" manage=off
yabai -m rule --add app="^mpv$" sticky=on layer=above manage=off
yabai -m rule --add app="^Microsoft Edge$" manage=on space=^1 mouse_follows_focus=on
yabai -m rule --add app="^Code$" layer=above manage=on space=^2 mouse_follows_focus=on
yabai -m rule --add app="^kitty|alacritty$" title="^Primary$" layer=above manage=on space=^3 mouse_follows_focus=on
yabai -m rule --add app="^kitty|alacritty$" title="^Secondary$" layer=above manage=on space=^6 mouse_follows_focus=on
yabai -m rule --add app="^Notion$" layer=above manage=on space=^7 mouse_follows_focus=on
yabai -m rule --add app="^Preview$" layer=above manage=on space=^8 mouse_follows_focus=on
yabai -m rule --add app="^Dash$" layer=above manage=on space=^8 mouse_follows_focus=on


# SIGNALS
STACKLINE_EVENTS="application_activated \
    application_front_switched \
    application_hidden \
    application_launched \
    application_terminated \
    application_visible \
    window_created \
    window_deminimized \
    window_focused \
    window_minimized \
    window_resized"

for event in $STACKLINE_EVENTS
do
    yabai -m signal --add event="$event" label="stackline_$event" app!="Hammerspoon" action="echo ':$event' | hs -m stackline-events"
done
yabai -m signal --add event="window_destroyed" label="stackline_window_destroyed" action="echo ':window_destroyed' | hs -m stackline-events"
yabai -m signal --add event=application_front_switched action="${functions[topmost_opacity]}"
yabai -m signal --add event=window_focused action="${functions[topmost_opacity]}"



echo "yabai configuration loaded.."
