# Set XDG dirs
export XDG_CONFIG_HOME=~/.config

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# Fix rendering issue with Java & bspwm
export _JAVA_AWT_WM_NONREPARENTING=1