#!/usr/bin/env bash


if [ $(uname -s) = "Darwin" ]; then
  ln -snfv $PWD/config/yabai $HOME/.config/yabai
  ln -snfv $PWD/config/hammerspoon $HOME/.config/hammerspoon  
fi

if [ $(uname -s) = "Linux" ]; then
  ln -snfv $PWD/config/bspwm $HOME/.config/bspwm
  ln -snfv $PWD/config/sxhkd $HOME/.config/sxhkd
  ln -snfv $PWD/config/polybar $HOME/.config/polybar
  ln -snfv $PWD/config/rofi $HOME/.config/rofi
fi

if [ -x "$(command -v kitty)" ]; then
  ln -snfv $PWD/config/kitty $HOME/.config/kitty
else
  ln -snfv $PWD/config/alacritty $HOME/.config/alacritty
fi

ln -snfv $PWD/config/fonts $HOME/.config/fonts
ln -snfv $PWD/config/fzf $HOME/.config/fzf
ln -snfv $PWD/config/mpv $HOME/.config/mpv
ln -snfv $PWD/config/nvim $HOME/.config/nvim
ln -snfv $PWD/config/tmux $HOME/.config/tmux
ln -snfv $PWD/config/vifm $HOME/.config/vifm
ln -snfv $PWD/config/zsh $HOME/.config/zsh
ln -snfv $PWD/config/lf $HOME/.config/lf