#!/usr/bin/env bash


if [ $(uname -s) = "Darwin" ]; then
  ln -Fvs $PWD/config/yabai $HOME/.config/yabai
  ln -Fvs $PWD/config/hammerspoon $HOME/.config/hammerspoon  
fi

if [ $(uname -s) = "Linux" ]; then
  ln -Fvs $PWD/config/bspwm $HOME/.config/bspwm
  ln -Fvs $PWD/config/sxhkd $HOME/.config/sxhkd
  ln -Fvs $PWD/config/polybar $HOME/.config/polybar
  ln -Fvs $PWD/config/rofi $HOME/.config/rofi
fi

ln -Fvs $PWD/config/alacritty $HOME/.config/alacritty
ln -Fvs $PWD/config/fonts $HOME/.config/fonts
ln -Fvs $PWD/config/fzf $HOME/.config/fzf
ln -Fvs $PWD/config/mpv $HOME/.config/mpv
ln -Fvs $PWD/config/nvim $HOME/.config/nvim
ln -Fvs $PWD/config/tmux $HOME/.config/tmux
ln -Fvs $PWD/config/vifm $HOME/.config/vifm
ln -Fvs $PWD/config/zsh $HOME/.config/zsh